GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/info
###
DELETE http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "aaaaa",
  "number": "111114"
}